config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :questions
  resources :quizzes

  root 'pages#home', as: 'home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  #has_many :scores
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :questions
  #has_one :user_score_quiz

  has_many :scores, as: :scoreable
  has_many :users, :through => :scoreable
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :scoreable, polymorphic: true
  define_attribute_methods

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :scores, as: :scoreable

  #has_one :user_score_quiz
  #has_many :quizzes, :through => :user_score_quiz
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home


	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    if current_user
      @questions = Question.all
    else
      redirect_to home_path
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show

  end



  # GET /questions/new
  def new
    @question = Question.new

  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update

    if params.has_key?(:question)
      @question.update_attributes(params[:question].permit(:role_ids))
    end
    respond_to do |format|

      if @question.update(question_params)

        if @question.answer == @question.guess

         #@question.quiz.scores.first.quiz_score = @question.quiz.scores.first.quiz_score + 1
         #@question.quiz.scores.last.increment(:quiz_score, by = 1)
         #@question.quiz.scores.first.update_attribute(:quiz_score, @question.quiz.scores.first.quiz_score += 1)
         @question.quiz.scores.last.update_attribute(:quiz_score, @question.quiz.scores.last.quiz_score += 1)
         @question.quiz.scores.last.save
          format.html { redirect_to @question, notice: 'Answer is correct. Current score: ' + @question.quiz.scores.last.quiz_score.to_s + ' of ' + current_user.email.split('@')[0].to_s}
          format.json { render :show, status: :ok, location: @question }
        else
          format.html { redirect_to @question, notice: 'Answer is incorrect. Correct choice is ' + @question.answer.to_s + ' ' + current_user.email.split('@')[0].to_s}
          format.json { render :show, status: :ok, location: @question }
        end
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:itemno, :quest_txt, :choice1, :choice2, :choice3, :choice4, :answer, :quiz_id, :guess)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all

  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show


  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new

  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
      if current_user
        created = Score.create
        created.update_attribute(:name, current_user.email.split('@')[0])
        created.save
        @quiz.scores.append(created)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:name)
    end
end

app/controllers/user_quiz_controller.rb
class UserQuizController < ApplicationController
  before_action :set_user_quiz

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_quiz
      @user_quiz = UserQuiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_quiz_params
      params.require(:user_quiz).permit(:score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/user_quiz_helper.rb
module UserQuizHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Larong Pinoy</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <div class="site-container">
      <nav class="navbar navbar-expand-lg navbar-light larong-pinoy-header fixed-top">
        <a class="navbar-brand" href="<%= home_path %>">
          <%= image_tag("/assets/tsinelas.png",  alt: "Larong Pinoy Slipper-P Logo" , class: "logo") %>
          <span class="font-weight-bold">Larong Pinoy</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if current_user %>
              <li class="nav-item active">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to 'Sign up', new_user_registration_path, :class => "nav-link" %>

              </li>
              <li class="nav-item active">
                <%= link_to 'Sign in', new_user_session_path, :class => "nav-link" %>
              </li>
              <% end %>
          </ul>
        </div>
      </nav>
      <%= render 'layouts/alerts' %>
      <%= yield %>

      <div class="p-3 text-center">
        <span class="">Application created by Arlan Uy and Menard Cruz for CS 173</span>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-100 h-100 d-flex">
	<div class="container m-auto d-flex">
		<div class="m-auto d-flex flex-column">
			<div class="d-flex">
				<%= image_tag("/assets/tsinelas.png",  alt: "Larong Pinoy Slipper-P Logo" , class: "logo-lg") %> 
				<span class=" my-auto ml-1 h3 font-weight-bold">Larong Pinoy</span>
			</div>
			<a href="<%= quizzes_path %>" class="mx-auto mt-3">
				<button class="btn btn-light btn-lg bg-yellow px-4" type="button">
					<span class="h2 font-weight-bold">PLAY</span>
				</button>
			</a>
		</div>	
	</div>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :itemno %>
    <%= form.number_field :itemno, id: :question_itemno %>
  </div>

  <div class="field">
    <%= form.label :quest_txt %>
    <%= form.text_field :quest_txt, id: :question_quest_txt %>
  </div>

  <div class="field">
    <%= form.label :choice1 %>
    <%= form.text_field :choice1, id: :question_choice1 %>
  </div>

  <div class="field">
    <%= form.label :choice2 %>
    <%= form.text_field :choice2, id: :question_choice2 %>
  </div>

  <div class="field">
    <%= form.label :choice3 %>
    <%= form.text_field :choice3, id: :question_choice3 %>
  </div>

  <div class="field">
    <%= form.label :choice4 %>
    <%= form.text_field :choice4, id: :question_choice4 %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :question_answer %>
  </div>



  <div class="field">
    <%= form.label :quiz_id %>
    <%= form.number_field :quiz_id, id: :question_quiz_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Itemno</th>
      <th>Quest txt</th>
      <th>Choice1</th>
      <th>Choice2</th>
      <th>Choice3</th>
      <th>Choice4</th>
      <th>Answer</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.itemno %></td>
        <td><%= question.quest_txt %></td>
        <td><%= question.choice1 %></td>
        <td><%= question.choice2 %></td>
        <td><%= question.choice3 %></td>
        <td><%= question.choice4 %></td>
        <td><%= question.answer %></td>
        <td><%= question.quiz_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="w-100 h-100 d-flex">
  <div class="container mt-5 d-flex">
    <div class="mt-5 d-flex flex-column w-100">
    
      <div class="row w-100">
        <div class="col-lg-6">
          <p class="h3 mt-4">
            <%= @question.quest_txt %>
          </p>

          
            <%= form_for @question do |f| %>

              <div class="my-4">
                <div class="field">
                  <%= f.radio_button :guess, @question.choice1 %>
                  <%= f.label :guess, "a. "+@question.choice1, :value => @question.choice1  %>
                </div>

                <div class="field">
                  <%= f.radio_button :guess, @question.choice2 %>
                  <%= f.label :guess, "b. "+@question.choice2, :value => @question.choice2 %>
                </div>

                <div class="field">  
                  <%= f.radio_button :guess, @question.choice3 %>
                  <%= f.label :guess, "c. "+@question.choice3, :value => @question.choice3 %>
                </div>

                <div class="field">
                  <%= f.radio_button :guess, @question.choice4 %>
                  <%= f.label :guess, "d. "+@question.choice4, :value => @question.choice4 %>
                </div>

              </div>

              <%= f.submit 'Submit answer', class: "ui right floated green submit button btn btn-success" %>
            <% end %>
           
        </div>
         <div class="col-lg-6 d-flex flex-column">
        
            <p class="text-center h2 font-weight-bold">
              <%= Quiz.where(id: @question.quiz_id).first.name %>
            </p>
            <div class="w-100 py-2 d-flex bg-yellow">
              <span class="mx-auto">Item No. <%= @question.itemno %>    </span>
            </div>


            <p id="notice" class="text-center text-white  

              <% if notice == "Answer is correct." %>
                bg-success
              <% else %>
                bg-danger
              <% end %>
            ">
              <%= notice %>
            </p>

            <div class="d-flex ml-auto mt-3">
              <%= link_to 'Next Question', Question.where(quiz_id: @question.quiz_id, itemno: (@question.itemno + 1)).take, class: "btn-light p-2" %>

              <% if current_user %>
                <span class="ml-3 mr-1 my-auto">
                  <%= link_to 'Edit', edit_question_path(@question) %>
                </span>
              <% end %>
            </div>


        </div>
      </div>
      

      

    </div>  
  </div>
</div>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :quiz_name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<div class="w-100 h-100 d-flex">
  <div class="container mt-5 d-flex">
    <div class="d-flex flex-column w-100">
      <p id="notice"><%= notice %></p>

      <h1 class="text-center">Quizzes</h1>
      <% if current_user %>
        <%= link_to 'New Quiz', new_quiz_path, class: "text-center" %>
      <% end %>

      <table>
        
        <tbody>
          <div class="row">
            <% @quizzes.each do |quiz| %>
              <div class="col-6 d-flex">
                <a href="<%= quiz_path(quiz) %>" class="d-flex mt-3 w-100">
                  <button class="btn btn-light btn-lg bg-yellow px-3 mx-auto " type="button">
                    <span class="h5"><%= quiz.name %></span>
                  </button>
                </a>

                <% if current_user %>

                  <%= link_to 'Edit', edit_quiz_path(quiz), class: "my-auto" %>
                  <%= link_to 'Destroy', quiz, method: :delete, class: "my-auto mx-3", data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          </div>
        </tbody>
      </table>

      <br>

      
    </div>  
  </div>
</div>

app/views/quizzes/new.html.erb
<div class="w-100 h-100 d-flex">
	<div class="container mt-5 d-flex">
		<div class="mt-4 d-flex flex-column">
			<h1 class="mb-4">New Quiz</h1>

			<%= render 'form', quiz: @quiz %>


			<%= link_to 'Back', quizzes_path %>
		</div>	
	</div>
</div>

app/views/quizzes/show.html.erb
<div class="w-100 h-100 d-flex">
	<div class="container mt-5 pt-5 d-flex">
		<div class="mt-5 mx-auto pt-5 d-flex flex-column">

			<p id="notice"><%= notice %></p>

			<h1 class="mb-4"><%= @quiz.name %></h1>

			<%= link_to 'Start Quiz', Question.where(quiz_id: @quiz.id).first, class: "btn btn-light bg-yellow" %>
			<tr> "High Scores"</tr>
			<% $scores_hash = Hash.new %>
			<% @quiz.scores.each do |score| %>
				<tr>
					<% $scores_hash[score.name] %>
				</tr>
				<tr>
					<%  score.quiz_score %>
				</tr>
				<% if not $scores_hash[score.name] %>
					<% $scores_hash[score.name] = score.quiz_score%>
				<% end %>
				<% if score.quiz_score > $scores_hash[score.name] %>
					<% $scores_hash[score.name] = score.quiz_score%>
				<% end %>
			<% end %>
			<% $scores_hash.sort_by(&:first).reverse %>
			<% $scores_hash.keys.each do |filtered_score| %>
				<tr>
					<td><%= filtered_score %></td>
					<td><%= $scores_hash[filtered_score]%></td>
				</tr>
			<% end %>
		</div>
	</div>
</div>